= sxmml MMLコマンドリファレンス
:toc: left

本書は、sxmmlで使用可能なMMLコマンドの仕様について説明するものである。
記載されているコマンドは、sxmmlにおいて実装済みまたは実装予定のものであり
対応していないMMLコマンドは含まれない。

== 基本事項

sxmmlは専用のMML記法を用いて他の音源ドライバー向けのMMLに変換を行うトランスレータである。
MMLコマンドは大きく通常のMML用のコマンドとリズム音源用のコマンドの2つに分かれている。

通常のMMLコマンドは コマンド名とパラメータの組み合わせで表現され、一部のコマンド以外は
"コマンド名{パラメータ}" の形で指定する。パラメータが数値のみで構成される場合 "{}" は省略可能である。

例外となるコマンドは以下の通り。

音程・休符はコマンドの直後に音長パラメータを記載し、 "{}" 内に音長指定を行う事は出来ない。
ポルタメントコマンドは "{}" によるパラメータ指定の直後に別途、音長を指定する。

リズム音源用のMMLコマンドはリズム楽器毎に同時に発音・設定を行えるようにするため、
"コマンド名{リズム楽器 ...}パラメータ" の形式で一括指定が可能となっている。
可読性を高めるため、リズム楽器は "{}" で括れるようになっているが省略も可能である。


== 発音・音長

=== 音符
==== 書式
....
a/b/c/d/e/f/g [+/-] ... [音長] [付点] ... [& 音長/付点 .../% tick数] ... 
a/b/c/d/e/f/g [+/-] ... % tick数 [& 音長/付点 .../% tick数] ...
....
==== 説明
指定した音高と長さで発音する。シャープやフラットの付加はそれぞれ+もしくは-を指定する。

記号(+/-)は複数付加しダブルシャープ・ダブルフラット(それ以上も)とすることができる。
音程と記号の間には空白を入れられない。
付点についても多重付点に対応しているが付点同士の間に空白を入れることはできない。

音長に数値nを指定した場合、全音符長に対するn分音符の音長を表す。
% に続けて数値を指定するとtick数を直接指定できる。この場合付点は付けられない。
音長を省略した場合はデフォルトの音長が使用される。デフォルト音長は l コマンドで指定できる。

& に続けて音長やtick数を指定することで、指定分の音長を加算することができる。

'''

=== 休符
==== 書式
....
r [音長] [付点] ... [& 音長/付点 .../% tick数] ...
r% tick数 [& 音長/付点 .../% tick数] ...
....
==== 説明
指定した長さだけ休む。

長さの指定は<<_音符,音符コマンド>>に凖じる。

'''

=== ポルタメント
==== 書式
....
/{開始音程 終了音程} [音長]
....
==== 説明
開始音程から終了音程に音長で指定された時間を使って滑らかに音を繋げる。

音長に指定できる内容は<<_音符,音符コマンド>>と同様である。
開始音程と終了音程にはa〜gの他、o, <, >コマンドによるオクターブの変更が可能。

'''

=== デフォルト音長設定
==== 書式
....
l{整数}
l 整数
....
==== 説明
a〜gおよびrコマンド、ポルタメントのデフォルト音長をn分音符単位で指定する。初期値は4。

'''

=== ゲートタイム
==== 書式
....
q{整数}
q 整数
....
==== 説明
音長から指定された値のtick数分早くキーオフされる。

'''

=== タイ・スラー
==== 書式
....
&
....
==== 説明
直前で指定された音をキーオフしない。

※直後に数値を続けた場合は<<_音符,音符コマンド>>等の音長加算となりこのコマンドは発行されない。

'''

=== パン
==== 書式
....
p{整数}
p 整数
....
==== 説明
左右の音の出力位置を指定する。数値の意味はバックエンドに依存する。


== 音高・デチューン

=== オクターブ指定
==== 書式
....
o{整数}
o 整数
....
==== 説明
オクターブを設定する。

sxmmlとしては範囲の制限はないが、実際に使用できる範囲はバックエンドやドライバに依存する。
デフォルト値は4。

'''

=== オクターブ変更
==== 書式
....
>
<
....
==== 説明
オクターブを1つ、上げたり下げたりする。

上げる時は ">" 下げる時は "<" を指定する。パラメータは取らない。
効果を反転させる機能は現状無い。

ループやリピートから先頭に戻った際にオクターブ設定は元に戻る。

※MMLを中間形式にコンパイルした際にオクターブ情報は音程に反映されオクターブという情報は存在しない。

'''

=== デチューン
==== 書式
....
D{整数}
D 整数
....
==== 説明
発音周波数をずらし微細な音程調整を行う。
正の整数で高い音、負の整数の設定で低い音となる。

'''

=== 移調
==== 書式
....
K{整数}
K 整数
....
==== 説明
指定された数値の分だけ音程の値を半音単位で変化させる。

'''

=== 移調相対変更
==== 書式
....
K*{整数}
K* 整数
....
==== 説明
現在の移調値からの相対的な変化量を指定する。

リピートコマンドと組み合わせてグリス等の表現に便利。

'''

=== 移調(コンパイラ)
==== 書式
....
K${整数}
K$ 整数
....
==== 説明
コンパイル時に指定された数値の分だけ音程の値を半音単位で変化させる。

※バックエンドやドライバに移調コマンドが渡されないためPCMドラム等のデータ削減に有効。


== ボリューム

=== ボリューム指定
==== 書式
....
v{整数}
v 整数
....
==== 説明
音量を指定する。

sxmmlとしては範囲の制限はないが、実際に使用できる範囲はバックエンドやドライバ、音源の種類に依存する。

'''

=== ボリューム相対変更
==== 書式
....
v*{整数}
v* 整数
....
==== 説明
音量を現在値から指定した値だけ増減させる。

'''

=== ボリューム相対増加
==== 書式
....
)
....
==== 説明
ボリュームを現在値からトラックパラメータ "volume-delta" の分だけ増加させる。

'''

=== ボリューム相対減少
==== 書式
....
(
....
==== 説明
ボリュームを現在値からトラックパラメータ "volume-delta" の分だけ減少させる。


== テンポ

=== BPM設定
==== 書式
....
t{整数}
t 整数
....
==== 説明
四分音符を1ビートとした時のBPMを指定する。

6/8拍子等のように1ビートが四分音符ではない場合には"BPM"を設定しても想定していたテンポにはならない。

実際のテンポはバックエンドやドライバ、音源の種類により誤差が生じることがある。

'''

=== テンポ設定
==== 書式
....
T{整数}
T 整数
....
==== 説明
バックエンドがテンポ設定に使用するタイマー等の値を直接設定する。

バックエンドによっては t コマンドと同じ効果の場合がある。


== 音色

=== 音色指定
==== 書式
....
@{定義名}
@ 整数
....
==== 説明
使用する音色を設定する。


== ループ・リピート

=== ループ
==== 書式
....
L
....
==== 説明
トラックのMMLが終了した時、指定の位置にループし繰り返し演奏する。

'''

=== リピート
==== 書式
....
[ commands1 [:] commands2 ]整数
....
==== 説明
設定した範囲を指定した回数だけ繰り返す。

"["でリピートの開始地点を指定し、"]"で終了地点を指定する。
リピート内に":"が指定されると、最終リピート時にその場所から終了地点の直後までジャンプする。
デフォルト音長設定、オクターブ、移調(コンパイラ)の値は脱出時の値を引き継ぐ。


== LFO

=== LFO指定
==== 書式
....
M{定義名 チャンネル}
M 整数
....
==== 説明
定義済のLFOを設定し、音程や音量に周期的な変化を加える。

LFOの有効化・無効化には、LFOスイッチON・OFFのコマンドを別途使用する必要がある。
LFOチャンネルの指定が無い場合にはバックエンドのデフォルトチャンネルが使用される。
LFOチャンネルを指定する際には"{}"は省略できない。

'''

=== LFOスイッチON
==== 書式
....
Mt[{チャンネル}]
Mt[整数]
....
==== 説明
指定されたチャンネルのLFOを有効化する。

LFOチャンネルの指定が無い場合にはバックエンドのデフォルトチャンネルが使用される。

'''

=== LFOスイッチOFF
==== 書式
....
Mf[{チャンネル}]
Mf[整数]
....
==== 説明
指定されたチャンネルのLFOを無効化する。

LFOチャンネルの指定が無い場合にはバックエンドのデフォルトチャンネルが使用される。
LFOを無効化し、音の変化を止める。


== エンベロープ

=== エンベロープ指定
==== 書式
....
E{定義名}
E 整数
....
==== 説明
定義済のエンベロープを設定し、音量の時間変化の制御を行う。


== SSG制御

=== 出力スイッチ
==== 書式
....
P{整数}
P 整数
....
==== 説明
SSGのトーン、ノイズ、ミックス出力を制御する。

* 1: トーン
* 2: ノイズ
* 3: ミックス

'''

=== ノイズ周波数
==== 書式
....
w{整数}
w 整数
....
==== 説明
SSGのノイズ出力周波数を設定する。数値が小さいと周波数の高い音となる。


== リズム音源制御

=== 発音
==== 書式
....
@{b|s|t|c|h|i} [音長] [付点] ... [& 音長/付点 .../% tick数] ...
@{b|s|t|c|h|i} % tick数 [& 音長/付点 .../% tick数] ...
@ b|s|t|c|h|i [音長] [付点] ... [& 音長/付点 .../% tick数] ...
@ b|s|t|c|h|i % tick数 [& 音長/付点 .../% tick数] ...
....
==== 説明
指定したリズム楽器を発音する。音長指定は<<_音符,音符コマンド>>に凖じる。


'''

=== 消音
==== 書式
....
!{b|s|t|c|h|i}
! b|s|t|c|h|i
....
==== 説明
指定した発音中のリズム楽器を停止する。


'''

=== ボリューム相対増加
==== 書式
....
){b|s|t|c|h|i} 整数
) b|s|t|c|h|i 整数
....
==== 説明
音量を現在値から指定した値だけ増加させる。
負の数を与えると増加ではなく減少する。

'''

=== ボリューム相対減少
==== 書式
....
({b|s|t|c|h|i} 整数
( b|s|t|c|h|i 整数
....
==== 説明
音量を現在値から指定した値だけ減少させる。
負の数を与えると減少ではなく増加する。
